### ISSUE TITLE
Feature request: Author comment space

### ISSUE THREAD

**Issue by s-fong** [Physiome/physiome-coko#5]
Have a place on the portal where authors can make notes directly to the editor/curator.
This commenting area could become available for submissions that required revisions, and the author would like to respond to issues directly. 
Currently, there is no way to talk to the curator, aside from email.

**Comment by metatoaster** [comment]
This one is looking to be extremely involved as I have no idea how the internal data model is linked together if we were to store a threaded conversation (I referenced the File linkage bit but it's not clear to me how to define the table or how things are actually linked, as none of the system internals we inherited are clearly documented anywhere, and this is becoming extremely frustrating to develop further).  Best I can do most likely is to apply something similar to the Notes field but it's a free form text field.

Anyway, I will attempt one more week, but I am nearly at the point of wanting to completely give up working on this code base.

**Comment by metatoaster** [comment]
Comments can be posted successfully to the database, but the association of the comments to the submission itself remains broken because I can't replicate how the file association to the submission was done as the implementation is hidden behind the graphql endpoint, and that it would actually be unwise to use the same method because how this effectively allows the arbitrary relinkage of comments.

**Comment by metatoaster** [comment]
This is now deployed to https://dev.submit.physiomeproject.org/

Please review.  No email is currently sent when comment is made, this can be arranged possibly.

**Comment by s-fong** [comment]
Thanks for your work on this @metatoaster!

After running some tests of the dev portal, and discussions with the ABI journal team, there are some suggestions:
- Correspondence space is not accessed when an author first receives revisions (i.e. the 'Manuscript Revision' page). They only access it after they click 'resubmit'. It may be clearer for authors that they can reach this space if it is visible on the Manuscript Revision page first.
- Author needs to click 'OK' button twice to log a comment in the correspondence space.
- is there a way for someone to edit their comment in that space, after it is lodged?
- Show a word or character count for the input fields.
- Emails should be sent out to the author and curators that a new comment is added.
- Is it possible to show a log of what has happened to their revision so far, in this correspondence space? Such as whether their submission is being looked at by an editor or a curator (anonymously).

I know this is asking a lot, so please do only what can be easily done. Thanks!

**Comment by metatoaster** [comment]
> - [x] Correspondence space is not accessed when an author first receives revisions (i.e. the 'Manuscript Revision' page). They only access it after they click 'resubmit'. It may be clearer for authors that they can reach this space if it is visible on the Manuscript Revision page first.

Yeah that should be fixed.

> 
> - [x] Author needs to click 'OK' button twice to log a comment in the correspondence space.

I tried to work around this, but it has everything to do with how React components have been set up in this project and just a massive pain to even get working in the first place. Spent a couple days struggling with this, before I settled on a workaround where the event is triggered on loss of focus, which is why the button is non-responsive as the input area lost focus (because React is redrawing the entire form right at that moment).

> 
> - [ ] is there a way for someone to edit their comment in that space, after it is lodged?

Probably, but will take another day.

> 
> - [x] Show a word or character count for the input fields.

I want to say it is possible, but due to how the React components are set up, every time an update happens the whole thing is redrawn, therefore causing the input text area to lose focus completely and makes typing extremely aggravating.

> 
> - [x] Emails should be sent out to the author and curators that a new comment is added.

This is planned.

> 
> * Is it possible to show a log of what has happened to their revision so far, in this correspondence space? Such as whether their submission is being looked at by an editor or a curator (anonymously).

This would be another annoying retrofit into the project.  I would much rather create a new system from scratch that I can reason over and that isn't built on top of Node.js.

**Comment by metatoaster** [comment]
Okay, correction, finally found the correct workaround to set this up, I can probably do the character count now, and fix the button needing two clicks.

**Comment by metatoaster** [comment]
Okay, I got 4/5 that I originally said I was going to do.  I am going to shelve the ability to edit comments because that is also building a bunch of new things and I am getting extremely sick and tired of writing code with a language that fundamentally do not work (yet people pretend it does because it largely looks like it works but trust me it does not).

**Comment by nickerso** [comment]
Thanks @metatoaster - that is looking great and things are working as far as we can test. Is this ready for promotion to production? Any further specific testing we should do?

**Comment by metatoaster** [comment]
I've been working on the production image since yesterday, hopefully ready to be deployed today or tomorrow.

**Comment by metatoaster** [comment]
Deployed to production.
